FROM node:16

# Defina o diretório de trabalho no container
WORKDIR /app

# Copie os arquivos package.json e package-lock.json (se disponível)
COPY package*.json ./

# Instale as dependências do projeto
RUN npm ci

# Copie os arquivos do projeto para o diretório de trabalho
COPY . .

# Exponha a porta que sua aplicação usa
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["node", "src/server.js"]